project_name: confluent

dist: dist

builds:
  - binary: confluent
    main: cmd/confluent/main.go
    flags:
      - -mod=readonly
      - -tags={{.Env.TAGS}}
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.host={{.Env.HOSTNAME}}
    gcflags:
      - all=-trimpath={{.Env.HOME}}/git
    asmflags:
      - all=-trimpath={{.Env.HOME}}/git

archives:
  - id: binary
    replacements: 
      linux: alpine
    format: binary
  - id: archive
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements: 
      linux: alpine
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: "{{ .ProjectName }}"
    files:
      - LICENSE
      - legal/**/*
